- name: Provisioning for meka.rs
  hosts: all
  pre_tasks:
    - include: roles/common/pre_tasks/main.yml
    - include: roles/docker/pre_tasks/main.yml
  roles:
    - common

- name: Provisioning for meka.rs
  hosts: vagrant
  roles:
    - vagrant

- name: Provisioning for meka.rs
  hosts: all
  roles:
    - blog
    - nginx
