---
- name: add nginx service
  sudo: yes
  template:
    src: nginx.service.j2
    dest: /lib/systemd/system/nginx.service
    owner: root
    group: root
  notify:
    - restart nginx

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload
