---
- name: create volume for blog
  become: yes
  file:
    path: /var/lib/docker/volumes/blog
    owner: "{{ rsync_user }}"
    group: "{{ rsync_group }}"
    state: directory

- name: copy site to server
  become: yes
  synchronize:
    src: ../site/output/
    dest: /var/lib/docker/volumes/blog
    delete: yes
  tags:
    - deploy
