---
- name: add services
  sudo: yes
  with_items: meka_services
  template:
    src: "{{ item.name }}.service.j2"
    dest: "/lib/systemd/system/{{ item.name }}.service"
    owner: root
    group: root

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: start services
  sudo: yes
  with_items: meka_services
  service:
    name: "{{ item.name }}"
    enabled: yes
    state: started
