---
- name: update apt
  become: yes
  apt:
    update_cache: yes

- name: install docker
  become: yes
  apt:
    name: docker.io
    state: latest

- name: start docker
  become: yes
  service:
    name: docker
    enabled: yes
    state: started
