---
galaxy_info:
  author: your name
  description:
  company: your company (optional)
  license: GPLv3
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
      - 7
  categories:
    - cloud
    - clustering
    - web
dependencies:
  - {role: common}
